from game.message.client.C_CHECK_VERSION import C_CHECK_VERSION
from game.message.client.C_COMBATLOG_USER_INFO_RESET import C_COMBATLOG_USER_INFO_RESET
from game.message.client.C_PLAYER_FLYING_LOCATION import C_PLAYER_FLYING_LOCATION
from game.message.client.C_PLAYER_LOCATION import C_PLAYER_LOCATION
from game.message.client.C_START_SKILL import C_START_SKILL
from game.message.client.C_START_SKILL_BY_VEHICLE_EX import C_START_SKILL_BY_VEHICLE_EX
from game.message.client.C_START_TARGETED_SKILL import C_START_TARGETED_SKILL
from game.message.client.C_USER_AIM import C_USER_AIM
from game.message.client.C_USER_AIM_TO import C_USER_AIM_TO
from game.message.client.C_VEHICLEEX_LOCATION import C_VEHICLEEX_LOCATION
from game.message.server.S_ABNORMALITY_BEGIN import S_ABNORMALITY_BEGIN
from game.message.server.S_ABNORMALITY_DAMAGE_ABSORB import S_ABNORMALITY_DAMAGE_ABSORB
from game.message.server.S_ABNORMALITY_END import S_ABNORMALITY_END
from game.message.server.S_ABNORMALITY_EXTRA import S_ABNORMALITY_EXTRA
from game.message.server.S_ABNORMALITY_REFRESH import S_ABNORMALITY_REFRESH
from game.message.server.S_ACTION_END import S_ACTION_END
from game.message.server.S_ACTION_STAGE import S_ACTION_STAGE
from game.message.server.S_ADD_CHARM_STATUS import S_ADD_CHARM_STATUS
from game.message.server.S_BAN_PARTY_MEMBER import S_BAN_PARTY_MEMBER
from game.message.server.S_BEGIN_THROUGH_ARBITER_CONTRACT import S_BEGIN_THROUGH_ARBITER_CONTRACT
from game.message.server.S_BOSS_GAGE_INFO import S_BOSS_GAGE_INFO
from game.message.server.S_CHANGE_DESTPOS_PROJECTILE import S_CHANGE_DESTPOS_PROJECTILE
from game.message.server.S_CHAT import S_CHAT
from game.message.server.S_COMBATLOG_ADD_VALUE import S_COMBATLOG_ADD_VALUE
from game.message.server.S_COMBATLOG_COMBAT_ENGAGED_MONSTER_LIST import S_COMBATLOG_COMBAT_ENGAGED_MONSTER_LIST
from game.message.server.S_COMBATLOG_CURRENT_AGGRO_LIST import S_COMBATLOG_CURRENT_AGGRO_LIST
from game.message.server.S_COMBATLOG_START import S_COMBATLOG_START
from game.message.server.S_COMBATLOG_USER_INFO import S_COMBATLOG_USER_INFO
from game.message.server.S_CREATURE_CHANGE_HP import S_CREATURE_CHANGE_HP
from game.message.server.S_CREATURE_LIFE import S_CREATURE_LIFE
from game.message.server.S_CREATURE_ROTATE import S_CREATURE_ROTATE
from game.message.server.S_DECREASE_COOLTIME_SKILL import S_DECREASE_COOLTIME_SKILL
from game.message.server.S_DESPAWN_NPC import S_DESPAWN_NPC
from game.message.server.S_DESPAWN_USER import S_DESPAWN_USER
from game.message.server.S_EACH_SKILL_RESULT import S_EACH_SKILL_RESULT
from game.message.server.S_ENABLE_CHARM_STATUS import S_ENABLE_CHARM_STATUS
from game.message.server.S_END_CHANGE_USER_APPEARANCE import S_END_CHANGE_USER_APPEARANCE
from game.message.server.S_END_USER_PROJECTILE import S_END_USER_PROJECTILE
from game.message.server.S_GET_USER_GUILD_LOGO import S_GET_USER_GUILD_LOGO
from game.message.server.S_GET_USER_LIST import S_GET_USER_LIST
from game.message.server.S_GRANT_SKILL import S_GRANT_SKILL
from game.message.server.S_GUILD_NAME import S_GUILD_NAME
from game.message.server.S_HIDE_HP import S_HIDE_HP
from game.message.server.S_HIT_COMBO import S_HIT_COMBO
from game.message.server.S_INSTANT_MOVE import S_INSTANT_MOVE
from game.message.server.S_LEAVE_PARTY import S_LEAVE_PARTY
from game.message.server.S_LEAVE_PARTY_MEMBER import S_LEAVE_PARTY_MEMBER
from game.message.server.S_LOGIN import S_LOGIN
from game.message.server.S_LOGIN_ACCOUNT_INFO import S_LOGIN_ACCOUNT_INFO
from game.message.server.S_LOGOUT_PARTY_MEMBER import S_LOGOUT_PARTY_MEMBER
from game.message.server.S_MOUNT_VEHICLE_EX import S_MOUNT_VEHICLE_EX
from game.message.server.S_NPC_LOCATION import S_NPC_LOCATION
from game.message.server.S_NPC_OCCUPIER_INFO import S_NPC_OCCUPIER_INFO
from game.message.server.S_NPC_STATUS import S_NPC_STATUS
from game.message.server.S_NPC_TARGET_USER import S_NPC_TARGET_USER
from game.message.server.S_PARTY_INFO import S_PARTY_INFO
from game.message.server.S_PARTY_MEMBER_ABNORMAL_ADD import S_PARTY_MEMBER_ABNORMAL_ADD
from game.message.server.S_PARTY_MEMBER_ABNORMAL_CLEAR import S_PARTY_MEMBER_ABNORMAL_CLEAR
from game.message.server.S_PARTY_MEMBER_ABNORMAL_DEL import S_PARTY_MEMBER_ABNORMAL_DEL
from game.message.server.S_PARTY_MEMBER_ABNORMAL_REFRESH import S_PARTY_MEMBER_ABNORMAL_REFRESH
from game.message.server.S_PARTY_MEMBER_BUFF_UPDATE import S_PARTY_MEMBER_BUFF_UPDATE
from game.message.server.S_PARTY_MEMBER_CHANGE_HP import S_PARTY_MEMBER_CHANGE_HP
from game.message.server.S_PARTY_MEMBER_CHANGE_MP import S_PARTY_MEMBER_CHANGE_MP
from game.message.server.S_PARTY_MEMBER_CHANGE_STAMINA import S_PARTY_MEMBER_CHANGE_STAMINA
from game.message.server.S_PARTY_MEMBER_CHARM_ADD import S_PARTY_MEMBER_CHARM_ADD
from game.message.server.S_PARTY_MEMBER_CHARM_DEL import S_PARTY_MEMBER_CHARM_DEL
from game.message.server.S_PARTY_MEMBER_CHARM_ENABLE import S_PARTY_MEMBER_CHARM_ENABLE
from game.message.server.S_PARTY_MEMBER_CHARM_RESET import S_PARTY_MEMBER_CHARM_RESET
from game.message.server.S_PARTY_MEMBER_INFO import S_PARTY_MEMBER_INFO
from game.message.server.S_PARTY_MEMBER_INTERVAL_POS_UPDATE import S_PARTY_MEMBER_INTERVAL_POS_UPDATE
from game.message.server.S_PARTY_MEMBER_LIST import S_PARTY_MEMBER_LIST
from game.message.server.S_PARTY_MEMBER_STAT_UPDATE import S_PARTY_MEMBER_STAT_UPDATE
from game.message.server.S_PARTY_NOTIFY_MY_POSITION import S_PARTY_NOTIFY_MY_POSITION
from game.message.server.S_PLAYER_CHANGE_ALL_PROF import S_PLAYER_CHANGE_ALL_PROF
from game.message.server.S_PLAYER_CHANGE_DRAIN import S_PLAYER_CHANGE_DRAIN
from game.message.server.S_PLAYER_CHANGE_EP import S_PLAYER_CHANGE_EP
from game.message.server.S_PLAYER_CHANGE_EXP import S_PLAYER_CHANGE_EXP
from game.message.server.S_PLAYER_CHANGE_FLIGHT_ENERGY import S_PLAYER_CHANGE_FLIGHT_ENERGY
from game.message.server.S_PLAYER_CHANGE_MP import S_PLAYER_CHANGE_MP
from game.message.server.S_PLAYER_CHANGE_NOCTAN_COUNT import S_PLAYER_CHANGE_NOCTAN_COUNT
from game.message.server.S_PLAYER_CHANGE_PROF import S_PLAYER_CHANGE_PROF
from game.message.server.S_PLAYER_CHANGE_STAMINA import S_PLAYER_CHANGE_STAMINA
from game.message.server.S_PLAYER_CHANGE_UNION_SKILL_COUNT import S_PLAYER_CHANGE_UNION_SKILL_COUNT
from game.message.server.S_PLAYER_RESET_EP import S_PLAYER_RESET_EP
from game.message.server.S_PLAYER_STAT_UPDATE import S_PLAYER_STAT_UPDATE
from game.message.server.S_PLAYER_VEHICLE_EX_STAT_UPDATE import S_PLAYER_VEHICLE_EX_STAT_UPDATE
from game.message.server.S_PRIVATE_CHAT import S_PRIVATE_CHAT
from game.message.server.S_REMOVE_CHARM_STATUS import S_REMOVE_CHARM_STATUS
from game.message.server.S_REQUEST_CONTRACT import S_REQUEST_CONTRACT
from game.message.server.S_RESET_CHARM_STATUS import S_RESET_CHARM_STATUS
from game.message.server.S_RESET_SKILL import S_RESET_SKILL
from game.message.server.S_SHOW_DEAD_UI import S_SHOW_DEAD_UI
from game.message.server.S_SHOW_HP import S_SHOW_HP
from game.message.server.S_SKILL_ATTENTION_TARGET import S_SKILL_ATTENTION_TARGET
from game.message.server.S_SKILL_CATEGORY import S_SKILL_CATEGORY
from game.message.server.S_SKILL_CHASE_EFFECT_TARGET import S_SKILL_CHASE_EFFECT_TARGET
from game.message.server.S_SKILL_FORGET import S_SKILL_FORGET
from game.message.server.S_SKILL_LEARN_LIST import S_SKILL_LEARN_LIST
from game.message.server.S_SKILL_LEARN_RESULT import S_SKILL_LEARN_RESULT
from game.message.server.S_SKILL_LIST import S_SKILL_LIST
from game.message.server.S_SKILL_PERIOD import S_SKILL_PERIOD
from game.message.server.S_SKILL_TARGETING_AREA import S_SKILL_TARGETING_AREA
from game.message.server.S_SPAWN_ME import S_SPAWN_ME
from game.message.server.S_SPAWN_NPC import S_SPAWN_NPC
from game.message.server.S_SPAWN_PROJECTILE import S_SPAWN_PROJECTILE
from game.message.server.S_SPAWN_USER import S_SPAWN_USER
from game.message.server.S_START_COOLTIME_SKILL import S_START_COOLTIME_SKILL
from game.message.server.S_START_USER_PROJECTILE import S_START_USER_PROJECTILE
from game.message.server.S_TARGET_INFO import S_TARGET_INFO
from game.message.server.S_TRADE_BROKER_DEAL_SUGGESTED import S_TRADE_BROKER_DEAL_SUGGESTED
from game.message.server.S_USER_AIM import S_USER_AIM
from game.message.server.S_USER_AIM_TO import S_USER_AIM_TO
from game.message.server.S_USER_APPEARANCE_CHANGE import S_USER_APPEARANCE_CHANGE
from game.message.server.S_USER_BLOCK_LIST import S_USER_BLOCK_LIST
from game.message.server.S_USER_CHANGE_NAME import S_USER_CHANGE_NAME
from game.message.server.S_USER_EFFECT import S_USER_EFFECT
from game.message.server.S_USER_EXTERNAL_CHANGE import S_USER_EXTERNAL_CHANGE
from game.message.server.S_USER_FLYING_LOCATION import S_USER_FLYING_LOCATION
from game.message.server.S_USER_ITEMLEVEL_INFO import S_USER_ITEMLEVEL_INFO
from game.message.server.S_USER_ITEM_EQUIP_CHANGER import S_USER_ITEM_EQUIP_CHANGER
from game.message.server.S_USER_LEVELUP import S_USER_LEVELUP
from game.message.server.S_USER_LOCATION import S_USER_LOCATION
from game.message.server.S_USER_LOCATION_IN_ACTION import S_USER_LOCATION_IN_ACTION
from game.message.server.S_USER_PAPERDOLL_INFO import S_USER_PAPERDOLL_INFO
from game.message.server.S_USER_REPORT import S_USER_REPORT
from game.message.server.S_USER_SITUATION import S_USER_SITUATION
from game.message.server.S_USER_STATUS import S_USER_STATUS
from game.message.server.S_WHISPER import S_WHISPER

def parse_opcodes(file):
    opcodes = {}
    with open('data/opcodes/' + file + '.txt') as f:
        for line in f:
            (val, key) = line.split(" = ")
            try:
                opcodes[int(key)] = eval(val)
            except Exception as e:
                # print(val, e)
                pass
    return opcodes