class S_PLAYER_STAT_UPDATE(object):

    def __init__(self, time, direction, opcode, reader, version):
        HpRemaining = reader.ReadInt32()
        MpRemaining = reader.ReadInt32()
        reader.Skip(4)
        TotalHp = reader.ReadInt32()
        TotalMp = reader.ReadInt32()
        return  # we don't need all other things now, but if we need - just remove return.
        BasePower = reader.ReadInt32()
        BaseEndurance = reader.ReadInt32()
        BaseImpactFactor = reader.ReadInt32()
        BaseBalanceFactor = reader.ReadInt32()
        BaseMovementSpeed = reader.ReadInt16()
        reader.Skip(2)
        BaseAttackSpeed = reader.ReadInt16()
        BaseCritRate = reader.ReadSingle()
        BaseCritResist = reader.ReadSingle()
        BaseCritPower = reader.ReadSingle()
        BaseAttack = reader.ReadInt32()
        BaseAttack2 = reader.ReadInt32()
        BaseDefence = reader.ReadInt32()
        BaseImpcat = reader.ReadInt32()
        BaseBalance = reader.ReadInt32()
        BaseResistWeakening = reader.ReadSingle()
        BaseResistPeriodic = reader.ReadSingle()
        BaseResistStun = reader.ReadSingle()
        BonusPower = reader.ReadInt32()
        BonusEndurance = reader.ReadInt32()
        BonusImpactFactor = reader.ReadInt32()
        BonusBalanceFactor = reader.ReadInt32()
        BonusMovementSpeed = reader.ReadInt16()
        reader.Skip(2)
        BonusAttackSpeed = reader.ReadInt16()
        BonusCritRate = reader.ReadSingle()
        BonusCritResist = reader.ReadSingle()
        BonusCritPower = reader.ReadSingle()
        BonusAttack = reader.ReadInt32()
        BonusAttack2 = reader.ReadInt32()
        BonusDefence = reader.ReadInt32()
        BonusImpcat = reader.ReadInt32()
        BonusBalance = reader.ReadInt32()
        BonusResistWeakening = reader.ReadSingle()
        BonusResistPeriodic = reader.ReadSingle()
        BonusResistStun = reader.ReadSingle()
        Level = reader.ReadInt32()
        Vitality = reader.ReadInt16()
        Status = reader.ReadByte()
        BonusHp = reader.ReadInt32()
        BonusMp = reader.ReadInt32()
        Stamina = reader.ReadInt32()
        TotalStamina = reader.ReadInt32()
        ReRemaining = reader.ReadInt32()
        TotalRe = reader.ReadInt32()
        reader.Skip(8)
        ItemLevelInventory = reader.ReadInt32()
        ItemLevel = reader.ReadInt32()
