from util import tipo
class S_PLAYER_STAT_UPDATE(object):

    def __init__(self, time, direction, opcode, reader, version):
        HpRemaining = reader.read(tipo.int32)
        MpRemaining = reader.read(tipo.int32)
        reader.skip(4)
        TotalHp = reader.read(tipo.int32)
        TotalMp = reader.read(tipo.int32)
        return  # we don't need all other things now, but if we need - just remove return.
        BasePower = reader.read(tipo.int32)
        BaseEndurance = reader.read(tipo.int32)
        BaseImpactFactor = reader.read(tipo.int32)
        BaseBalanceFactor = reader.read(tipo.int32)
        BaseMovementSpeed = reader.read(tipo.int16)
        reader.skip(2)
        BaseAttackSpeed = reader.read(tipo.int16)
        BaseCritRate = reader.read(tipo.float)
        BaseCritResist = reader.read(tipo.float)
        BaseCritPower = reader.read(tipo.float)
        BaseAttack = reader.read(tipo.int32)
        BaseAttack2 = reader.read(tipo.int32)
        BaseDefence = reader.read(tipo.int32)
        BaseImpcat = reader.read(tipo.int32)
        BaseBalance = reader.read(tipo.int32)
        BaseResistWeakening = reader.read(tipo.float)
        BaseResistPeriodic = reader.read(tipo.float)
        BaseResistStun = reader.read(tipo.float)
        BonusPower = reader.read(tipo.int32)
        BonusEndurance = reader.read(tipo.int32)
        BonusImpactFactor = reader.read(tipo.int32)
        BonusBalanceFactor = reader.read(tipo.int32)
        BonusMovementSpeed = reader.read(tipo.int16)
        reader.skip(2)
        BonusAttackSpeed = reader.read(tipo.int16)
        BonusCritRate = reader.read(tipo.float)
        BonusCritResist = reader.read(tipo.float)
        BonusCritPower = reader.read(tipo.float)
        BonusAttack = reader.read(tipo.int32)
        BonusAttack2 = reader.read(tipo.int32)
        BonusDefence = reader.read(tipo.int32)
        BonusImpcat = reader.read(tipo.int32)
        BonusBalance = reader.read(tipo.int32)
        BonusResistWeakening = reader.read(tipo.float)
        BonusResistPeriodic = reader.read(tipo.float)
        BonusResistStun = reader.read(tipo.float)
        Level = reader.read(tipo.int32)
        Vitality = reader.read(tipo.int16)
        Status = reader.read(tipo.byte)
        BonusHp = reader.read(tipo.int32)
        BonusMp = reader.read(tipo.int32)
        Stamina = reader.read(tipo.int32)
        TotalStamina = reader.read(tipo.int32)
        ReRemaining = reader.read(tipo.int32)
        TotalRe = reader.read(tipo.int32)
        reader.skip(8)
        ItemLevelInventory = reader.read(tipo.int32)
        ItemLevel = reader.read(tipo.int32)


#     def __init__(self, time, direction, opcode, data, version):
#         cur_hp = data.read(tipo.int32)
#         cur_mp = data.read(tipo.int32)
#         unk1 = data.read(tipo.int32)
#         max_hp = data.read(tipo.int32)
#         max_mp = data.read(tipo.int32)
#         base_power = data.read(tipo.int32)
#         base_endurance = data.read(tipo.int32)
#         base_impact_factor = data.read(tipo.int32)
#         base_balance_factor = data.read(tipo.int32)
#         base_movement_speed = data.read(tipo.int16)
#         unk2 = data.read(tipo.int16)
#         base_attack_speed = data.read(tipo.int16)
#         base_crit_rate = data.read(tipo.float)
#         base_crit_resist = data.read(tipo.float)
#         base_crit_power = data.read(tipo.float)
#         base_attack = data.read(tipo.int32)
#         base_attack2 = data.read(tipo.int32)
#         base_defense = data.read(tipo.int32)
#         base_impact = data.read(tipo.int32)
#         base_balance = data.read(tipo.int32)
#         base_resist_weakening = data.read(tipo.float)
#         base_resist_periodic = data.read(tipo.float)
#         base_resist_stun = data.read(tipo.float)
#         bonus_power = data.read(tipo.int32)
#         bonus_endurance = data.read(tipo.int32)
#         bonus_impact_factor = data.read(tipo.int32)
#         bonus_balance_factor = data.read(tipo.int32)
#         bonus_movement_speed = data.read(tipo.int16)
#         unk3 = data.read(tipo.int16)
#         bonus_attack_speed = data.read(tipo.int16)
#         bonus_crit_rate = data.read(tipo.float)
#         bonus_crit_resist = data.read(tipo.float)
#         bonus_crit_power = data.read(tipo.float)
#         bonus_attack = data.read(tipo.int32)
#         bonus_attack2 = data.read(tipo.int32)
#         bonus_defense = data.read(tipo.int32)
#         bonus_impact = data.read(tipo.int32)
#         bonus_balance = data.read(tipo.int32)
#         bonus_resist_weakening = data.read(tipo.float)
#         bonus_resist_periodic = data.read(tipo.float)
#         bonus_resist_stun = data.read(tipo.float)
#         level = data.read(tipo.int32)
#         vitality = data.read(tipo.int16)
#         status = data.read(tipo.byte)
#         bonus_hp = data.read(tipo.int32)
#         bonus_mp = data.read(tipo.int32)
#         cur_stamina = data.read(tipo.int32)
#         max_stamina = data.read(tipo.int32)
#         cur_re = data.read(tipo.int32)
#         max_re = data.read(tipo.int32)
#         unk5 = data.read(tipo.int32)
#         unk6 = data.read(tipo.int32)
#         item_level_inventory = data.read(tipo.int32)
#         item_level = data.read(tipo.int32)
#         unk7 = data.read(tipo.int32)
#         unk8 = data.read(tipo.int32)
#         unk9 = data.read(tipo.int32) # 0x1F40 = 8000
#         unk10 = data.read(tipo.int32) # 3
#         unk11 = data.read(tipo.int32)